# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(1082, 791)
        MainWindow.setStyleSheet("* {\n"
"    font: 16pt \"Arial\";\n"
"    background-color: #F2F4FF;\n"
"}\n"
"\n"
"#main_titulo, #layout_1 {\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background-color: #4864E6;\n"
"}\n"
"\n"
"#scrollArea {\n"
"    border: none;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#lbl_simplex {\n"
"    font: 75 24pt \"Arial\";\n"
"    color: #F2F4FF;\n"
"    background-color: #4864E6;\n"
"}\n"
"\n"
"#lbl, #lbl_2 {\n"
"    color: #F2F4FF;\n"
"    background-color: #4864E6;\n"
"}\n"
"\n"
"#btn_aceptar_1, #btn_aceptar_2, #btn_aceptar_3 {\n"
"    border: 1px solid #4864E6;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(250, 250, 250);\n"
"}\n"
"\n"
"#btn_aceptar_1:hover, #btn_aceptar_2:hover, #btn_aceptar_3:hover {\n"
"    background-color: rgb(225, 225, 225);\n"
"}\n"
"\n"
"#btn_aceptar_1:pressed, #btn_aceptar_2:pressed, #btn_aceptar_3:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(1060, 700))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 11, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 10, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 0, 10, 1)
        self.layout_1 = QtWidgets.QWidget(self.page)
        self.layout_1.setObjectName("layout_1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layout_1)
        self.gridLayout_4.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_4.setSpacing(8)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem4, 6, 1, 1, 1)
        self.spinRestricciones = QtWidgets.QSpinBox(self.layout_1)
        self.spinRestricciones.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spinRestricciones.setFont(font)
        self.spinRestricciones.setPrefix("")
        self.spinRestricciones.setMinimum(1)
        self.spinRestricciones.setMaximum(10)
        self.spinRestricciones.setObjectName("spinRestricciones")
        self.gridLayout_4.addWidget(self.spinRestricciones, 5, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 8, 1, 1, 1)
        self.lbl = QtWidgets.QLabel(self.layout_1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lbl.setFont(font)
        self.lbl.setObjectName("lbl")
        self.gridLayout_4.addWidget(self.lbl, 1, 1, 1, 1)
        self.lbl_2 = QtWidgets.QLabel(self.layout_1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.lbl_2.setFont(font)
        self.lbl_2.setObjectName("lbl_2")
        self.gridLayout_4.addWidget(self.lbl_2, 4, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 0, 0, 9, 1)
        self.btn_aceptar_1 = QtWidgets.QPushButton(self.layout_1)
        self.btn_aceptar_1.setMinimumSize(QtCore.QSize(0, 55))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.btn_aceptar_1.setFont(font)
        self.btn_aceptar_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_aceptar_1.setObjectName("btn_aceptar_1")
        self.gridLayout_4.addWidget(self.btn_aceptar_1, 7, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem7, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 0, 2, 9, 1)
        self.spinVariables = QtWidgets.QSpinBox(self.layout_1)
        self.spinVariables.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spinVariables.setFont(font)
        self.spinVariables.setPrefix("")
        self.spinVariables.setMinimum(1)
        self.spinVariables.setMaximum(10)
        self.spinVariables.setObjectName("spinVariables")
        self.gridLayout_4.addWidget(self.spinVariables, 2, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem9, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.layout_1, 2, 1, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.hL = QtWidgets.QHBoxLayout()
        self.hL.setContentsMargins(8, 8, 8, 8)
        self.hL.setSpacing(8)
        self.hL.setObjectName("hL")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hL.addItem(spacerItem10)
        self.btn_aceptar_2 = QtWidgets.QPushButton(self.page_2)
        self.btn_aceptar_2.setMinimumSize(QtCore.QSize(300, 55))
        self.btn_aceptar_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_aceptar_2.setObjectName("btn_aceptar_2")
        self.hL.addWidget(self.btn_aceptar_2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hL.addItem(spacerItem11)
        self.gridLayout_3.addLayout(self.hL, 5, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem12, 1, 2, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1038, 583))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lay = QtWidgets.QFormLayout()
        self.lay.setSpacing(8)
        self.lay.setObjectName("lay")
        self.gridLayout_5.addLayout(self.lay, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.textEdit = QtWidgets.QTextEdit(self.page_3)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_6.addWidget(self.textEdit, 0, 0, 1, 1)
        self.boton = QtWidgets.QWidget(self.page_3)
        self.boton.setObjectName("boton")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.boton)
        self.horizontalLayout.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.btn_aceptar_3 = QtWidgets.QPushButton(self.boton)
        self.btn_aceptar_3.setMinimumSize(QtCore.QSize(300, 55))
        self.btn_aceptar_3.setObjectName("btn_aceptar_3")
        self.horizontalLayout.addWidget(self.btn_aceptar_3)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.gridLayout_6.addWidget(self.boton, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.gridLayout_2.addWidget(self.stackedWidget, 2, 0, 1, 3)
        self.main_titulo = QtWidgets.QWidget(self.centralwidget)
        self.main_titulo.setObjectName("main_titulo")
        self.titulo = QtWidgets.QHBoxLayout(self.main_titulo)
        self.titulo.setContentsMargins(8, 8, 8, 8)
        self.titulo.setSpacing(8)
        self.titulo.setObjectName("titulo")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.titulo.addItem(spacerItem15)
        self.lbl_simplex = QtWidgets.QLabel(self.main_titulo)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lbl_simplex.setFont(font)
        self.lbl_simplex.setObjectName("lbl_simplex")
        self.titulo.addWidget(self.lbl_simplex)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.titulo.addItem(spacerItem16)
        self.gridLayout_2.addWidget(self.main_titulo, 0, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl.setText(_translate("MainWindow", "Número de variables"))
        self.lbl_2.setText(_translate("MainWindow", "Número de restricciones"))
        self.btn_aceptar_1.setText(_translate("MainWindow", "Aceptar"))
        self.btn_aceptar_2.setText(_translate("MainWindow", "Aceptar"))
        self.btn_aceptar_3.setText(_translate("MainWindow", "Volver al inicio"))
        self.lbl_simplex.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Simplex</p></body></html>"))
